# Generated by Django 5.0.1 on 2024-02-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='terms_accept',
            field=models.DateTimeField(blank=True, null=True, verbose_name='terms_accept'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='type_doc',
            field=models.CharField(blank=True, choices=[('0', 'CPF'), ('1', 'CNPJ')], max_length=1, null=True, verbose_name='type document'),
        ),
    ]
