# Generated by Django 5.0.1 on 2024-02-03 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usermodel_terms_accept_alter_usermodel_type_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalizatiionUserModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('country', models.CharField(max_length=50, verbose_name='Pais')),
                ('state', models.CharField(max_length=50, verbose_name='Estado')),
                ('city', models.CharField(max_length=50, verbose_name='Cidade')),
                ('district', models.CharField(max_length=50, verbose_name='Bairro')),
                ('street', models.CharField(max_length=100, verbose_name='Endereço')),
                ('number', models.IntegerField(verbose_name='Numero')),
                ('complement', models.TextField(blank=True, null=True, verbose_name='Complemento')),
                ('reference', models.TextField(blank=True, null=True, verbose_name='Ponto de referência')),
                ('postal_code', models.CharField(max_length=10, verbose_name='CEP')),
                ('main', models.BooleanField(default=True, verbose_name='Principal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
    ]
