# Generated by Django 5.0.1 on 2024-02-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usermodel_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
