# Generated by Django 5.0.1 on 2024-02-04 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_usermodel_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocalizatiionUserModel',
            new_name='LocalizationUserModel',
        ),
    ]
