# Generated by Django 5.0.1 on 2024-02-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_localizatiionusermodel_localizationusermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='token_firebase',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
