# Generated by Django 5.0.1 on 2024-03-19 00:26

import main.helpers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_usermodel_token_firebase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="photo_profile",
            field=models.FileField(
                upload_to=main.helpers.photo_profile_directory_path,
                verbose_name="Photo Profile",
            ),
        ),
    ]
