# Generated by Django 5.0.1 on 2024-05-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_localizationusermodel_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="document",
            field=models.CharField(
                blank=True,
                max_length=17,
                null=True,
                unique=True,
                verbose_name="document",
            ),
        ),
    ]
