# Generated by Django 5.0.1 on 2024-05-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_usermodel_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="type_doc",
            field=models.CharField(
                blank=True,
                choices=[("0", "CPF"), ("1", "CNPJ"), ("9", "--")],
                max_length=1,
                null=True,
                verbose_name="type document",
            ),
        ),
    ]
