services:
  web:
    build: .
    restart: always
    container_name: server_backend
    command: uvicorn main.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/code

    environment:
      - DATABASE_HOST=database-1.cny8eseo2ys0.us-east-1.rds.amazonaws.com
      - DATABASE_USER=postgres
      - DATABASE_PASS=XvfDLhgzElW4pDHnv9CC
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres

    ports:
      - 80:8000
    
    # depends_on:
    #   - db
    #   - redis

  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: 1234
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: sys_clepy_db

  #   ports: 
  #     - "5434:5432"

  #   volumes:
  #     - postgres_db:/var/lib/postgresql/data

  # nginx:
  #   build: ./nginx
  #   restart: always
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - web

  # redis:
  #   image: redis
  #   restart: always
  #   ports:
  #     - "6379:6379"

  #   command: redis-server --save 20 1 --loglevel debug --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81    

  #   volumes:
  #     - cache:/data

volumes:
  postgres_db:
    external: true

  cache:
    external: true