# Generated by Django 5.0.1 on 2024-02-03 23:36

import django.db.models.deletion
import main.helpers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='Price')),
                ('model', models.CharField(max_length=65, verbose_name='Model')),
                ('status', models.CharField(choices=[('0', 'WAITING'), ('1', 'APPROVED'), ('2', 'DISAPPROVED')], default='0', max_length=2, verbose_name='Status')),
                ('new', models.BooleanField(default=True, verbose_name='New')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Weight')),
                ('dimension', models.CharField(blank=True, default='15x15x15', max_length=30, null=True, verbose_name='Dimension')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.categorymodel', verbose_name='Categorias')),
                ('user_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Owner')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='PhotoProductModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('photo', models.ImageField(upload_to=main.helpers.photo_product_directory_path, verbose_name='photo')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productmodel')),
            ],
            options={
                'verbose_name': 'Photo Product',
                'verbose_name_plural': 'Photo Products',
            },
        ),
    ]
