# Generated by Django 5.0.1 on 2024-04-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_productmodel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photoproductmodel",
            name="order",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
