# Generated by Django 5.0.1 on 2024-04-30 22:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_photoproductmodel_order"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="photoproductmodel",
            unique_together=set(),
        ),
    ]
