# Generated by Django 5.0.1 on 2024-05-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_alter_photoproductmodel_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmodel",
            name="new",
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="dimension",
            field=models.CharField(
                blank=True,
                default="00x00x00",
                max_length=30,
                null=True,
                verbose_name="Dimension",
            ),
        ),
    ]
