# Generated by Django 5.0.1 on 2024-06-01 20:08

import django_resized.forms
import main.helpers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_remove_productmodel_new_alter_productmodel_dimension"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photoproductmodel",
            name="photo",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="PNG",
                keep_meta=True,
                quality=75,
                scale=0.5,
                size=[900, 700],
                upload_to=main.helpers.photo_product_directory_path,
                verbose_name="photo",
            ),
        ),
    ]
